# Generated by Django 3.2.14 on 2022-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220727_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='one_click_purchasing',
            new_name='is_others',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='paystack_customer_id',
            new_name='school_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
